databricks:
  catalog_name: data_engineering_prod
  schema_name: strava
  secret_scope: strava_dev_scope
  athlete_profile:
    raw_table:
      raw_table_name: strava_athlete_profile_raw
      raw_checkpoint_path: /Volumes/data_engineering_prod/strava/strava_athlete_raw
    cleanse_table:
      cleanse_table_name: strava_athlete_profile_cleanse
      cleanse_checkpoint_path: /Volumes/data_engineering_prod/strava/strava_athlete_cleanse
  athlete_activities:
    raw_table:
      raw_table_name: strava_athlete_activities_raw
      raw_checkpoint_path: /Volumes/data_engineering_prod/strava/strava_athlete_activities_raw
    cleanse_table:
      cleanse_table_name: strava_athlete_activities_cleanse
      cleanse_checkpoint_path: /Volumes/data_engineering_prod/strava/strava_athlete_cleanse
  token_table:
    token_table_name: strava_athelete_tokens
  calendar_dimension:
    table_name: cal_dim

strava_api:
  client_id: 186544
  athlete_profile_scope: activity:read_all